// Code generated by protoc-gen-starpc-rust. DO NOT EDIT.
// protoc-gen-starpc-rust version: v0.45.1-0.20260203090429-3e915608d4e8
// source: github.com/aperturerobotics/common/example/example.proto

#[allow(unused_imports)]
use starpc::StreamExt;

/// Service ID for Echoer.
pub const ECHOER_SERVICE_ID: &str = "example.Echoer";

/// Client trait for Echoer.
#[starpc::async_trait]
pub trait EchoerClient: Send + Sync {
    /// Echo.
    async fn echo(&self, request: &EchoMsg) -> starpc::Result<EchoMsg>;
}

/// Client implementation for Echoer.
pub struct EchoerClientImpl<C> {
    client: C,
}

impl<C: starpc::Client> EchoerClientImpl<C> {
    /// Creates a new client.
    pub fn new(client: C) -> Self {
        Self { client }
    }
}

#[starpc::async_trait]
impl<C: starpc::Client + 'static> EchoerClient for EchoerClientImpl<C> {
    async fn echo(&self, request: &EchoMsg) -> starpc::Result<EchoMsg> {
        self.client.exec_call("example.Echoer", "Echo", request).await
    }
}

/// Server trait for Echoer.
#[starpc::async_trait]
pub trait EchoerServer: Send + Sync {
    /// Echo.
    async fn echo(&self, request: EchoMsg) -> starpc::Result<EchoMsg>;
}

const ECHOER_METHOD_IDS: &[&str] = &[
    "Echo",
];

/// Handler for Echoer.
pub struct EchoerHandler<S: EchoerServer> {
    server: std::sync::Arc<S>,
}

impl<S: EchoerServer + 'static> EchoerHandler<S> {
    /// Creates a new handler wrapping the server implementation.
    pub fn new(server: S) -> Self {
        Self { server: std::sync::Arc::new(server) }
    }

    /// Creates a new handler with a shared server.
    pub fn with_arc(server: std::sync::Arc<S>) -> Self {
        Self { server }
    }
}

#[starpc::async_trait]
impl<S: EchoerServer + 'static> starpc::Invoker for EchoerHandler<S> {
    async fn invoke_method(
        &self,
        _service_id: &str,
        method_id: &str,
        stream: Box<dyn starpc::Stream>,
    ) -> (bool, starpc::Result<()>) {
        match method_id {
            "Echo" => {
                let request: EchoMsg = match stream.msg_recv().await {
                    Ok(r) => r,
                    Err(e) => return (true, Err(e)),
                };
                match self.server.echo(request).await {
                    Ok(response) => {
                        if let Err(e) = stream.msg_send(&response).await {
                            return (true, Err(e));
                        }
                        (true, Ok(()))
                    }
                    Err(e) => (true, Err(e)),
                }
            }
            _ => (false, Err(starpc::Error::Unimplemented)),
        }
    }
}

impl<S: EchoerServer + 'static> starpc::Handler for EchoerHandler<S> {
    fn service_id(&self) -> &'static str {
        "example.Echoer"
    }

    fn method_ids(&self) -> &'static [&'static str] {
        ECHOER_METHOD_IDS
    }
}

