// @generated by protoc-gen-es-lite unknown with parameter "ts_nocheck=false,target=ts"
// @generated from file github.com/aperturerobotics/common/example/example.proto (package example, syntax proto3)
 

import { OtherMsg } from './other/other.pb.js'
import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType, ScalarType } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'example'

/**
 * ExampleMsg is an example message.
 *
 * @generated from message example.ExampleMsg
 */
export interface ExampleMsg {
  /**
   * ExampleField is an example field.
   *
   * @generated from field: string example_field = 1;
   */
  exampleField?: string
  /**
   * OtherMsg is an example of an imported message field.
   *
   * @generated from field: example.other.OtherMsg other_msg = 2;
   */
  otherMsg?: OtherMsg
}

// ExampleMsg contains the message type declaration for ExampleMsg.
export const ExampleMsg: MessageType<ExampleMsg> = createMessageType({
  typeName: 'example.ExampleMsg',
  fields: [
    { no: 1, name: 'example_field', kind: 'scalar', T: ScalarType.STRING },
    { no: 2, name: 'other_msg', kind: 'message', T: () => OtherMsg },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})

/**
 * EchoMsg is the message body for Echo.
 *
 * @generated from message example.EchoMsg
 */
export interface EchoMsg {
  /**
   * @generated from field: string body = 1;
   */
  body?: string
}

// EchoMsg contains the message type declaration for EchoMsg.
export const EchoMsg: MessageType<EchoMsg> = createMessageType({
  typeName: 'example.EchoMsg',
  fields: [
    { no: 1, name: 'body', kind: 'scalar', T: ScalarType.STRING },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
