// @generated
// This file is @generated by prost-build.
/// ExampleMsg is an example message.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExampleMsg {
    /// ExampleField is an example field.
    #[prost(string, tag="1")]
    pub example_field: ::prost::alloc::string::String,
    /// OtherMsg is an example of an imported message field.
    #[prost(message, optional, tag="2")]
    pub other_msg: ::core::option::Option<other::OtherMsg>,
}
/// EchoMsg is the message body for Echo.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EchoMsg {
    #[prost(string, tag="1")]
    pub body: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
