// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/common/example/example.proto (package example, syntax proto3)
/* eslint-disable */

import { OtherMsg } from './other/other.pb.js'
import type { MessageType } from '@aptre/protobuf-es-lite/message'
import { createMessageType } from '@aptre/protobuf-es-lite/message'
import { ScalarType } from '@aptre/protobuf-es-lite/scalar'
import type { PartialFieldInfo } from '@aptre/protobuf-es-lite/field'

export const protobufPackage = 'example'

/**
 * ExampleMsg is an example message.
 *
 * @generated from message example.ExampleMsg
 */
export interface ExampleMsg {
  /**
   * ExampleField is an example field.
   *
   * @generated from field: string example_field = 1;
   */
  exampleField?: string
  /**
   * OtherMsg is an example of an imported message field.
   *
   * @generated from field: example.other.OtherMsg other_msg = 2;
   */
  otherMsg?: OtherMsg
}

export const ExampleMsg: MessageType<ExampleMsg> =
  /* @__PURE__ */ createMessageType({
    typeName: 'example.ExampleMsg',
    fields: [
      { no: 1, name: 'example_field', kind: 'scalar', T: ScalarType.STRING },
      { no: 2, name: 'other_msg', kind: 'message', T: () => OtherMsg },
    ] satisfies readonly PartialFieldInfo[],
    packedByDefault: true,
  })

/**
 * EchoMsg is the message body for Echo.
 *
 * @generated from message example.EchoMsg
 */
export interface EchoMsg {
  /**
   * @generated from field: string body = 1;
   */
  body?: string
}

export const EchoMsg: MessageType<EchoMsg> = /* @__PURE__ */ createMessageType({
  typeName: 'example.EchoMsg',
  fields: [
    { no: 1, name: 'body', kind: 'scalar', T: ScalarType.STRING },
  ] satisfies readonly PartialFieldInfo[],
  packedByDefault: true,
})
