// @generated by protoc-gen-es-starpc none with parameter "ts_nocheck=false,target=ts"
// @generated from file github.com/aperturerobotics/common/example/example.proto (package example, syntax proto3)
/* eslint-disable */

import { EchoMsg } from './example.pb.js'
import { MethodKind } from '@aptre/protobuf-es-lite'
import { ProtoRpc } from 'starpc'

/**
 * Echoer service returns the given message.
 *
 * @generated from service example.Echoer
 */
export const EchoerDefinition = {
  typeName: 'example.Echoer',
  methods: {
    /**
     * Echo returns the given message.
     *
     * @generated from rpc example.Echoer.Echo
     */
    Echo: {
      name: 'Echo',
      I: EchoMsg,
      O: EchoMsg,
      kind: MethodKind.Unary,
    },
  },
} as const

/**
 * Echoer service returns the given message.
 *
 * @generated from service example.Echoer
 */
export interface Echoer {
  /**
   * Echo returns the given message.
   *
   * @generated from rpc example.Echoer.Echo
   */
  Echo(request: EchoMsg, abortSignal?: AbortSignal): Promise<EchoMsg>
}

export const EchoerServiceName = EchoerDefinition.typeName

export class EchoerClient implements Echoer {
  private readonly rpc: ProtoRpc
  private readonly service: string
  constructor(rpc: ProtoRpc, opts?: { service?: string }) {
    this.service = opts?.service || EchoerServiceName
    this.rpc = rpc
    this.Echo = this.Echo.bind(this)
  }
  /**
   * Echo returns the given message.
   *
   * @generated from rpc example.Echoer.Echo
   */
  async Echo(request: EchoMsg, abortSignal?: AbortSignal): Promise<EchoMsg> {
    const requestMsg = EchoMsg.create(request)
    const result = await this.rpc.request(
      this.service,
      EchoerDefinition.methods.Echo.name,
      EchoMsg.toBinary(requestMsg),
      abortSignal || undefined,
    )
    return EchoMsg.fromBinary(result)
  }
}
