// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.2.1
// source: github.com/aperturerobotics/ts-common/example/example.proto

package example

import (
	fmt "fmt"
	io "io"

	protohelpers "github.com/aperturerobotics/protobuf-go-lite/protohelpers"
	other "github.com/aperturerobotics/ts-common/example/other"
)

// ExampleMsg is an example message.
type ExampleMsg struct {
	unknownFields []byte
	// ExampleField is an example field.
	ExampleField string `protobuf:"bytes,1,opt,name=example_field,json=exampleField,proto3" json:"example_field,omitempty"`
	// OtherMsg is an example of an imported message field.
	OtherMsg *other.OtherMsg `protobuf:"bytes,2,opt,name=other_msg,json=otherMsg,proto3" json:"other_msg,omitempty"`
}

func (x *ExampleMsg) Reset() {
	*x = ExampleMsg{}
}

func (*ExampleMsg) ProtoMessage() {}

func (x *ExampleMsg) GetExampleField() string {
	if x != nil {
		return x.ExampleField
	}
	return ""
}

func (x *ExampleMsg) GetOtherMsg() *other.OtherMsg {
	if x != nil {
		return x.OtherMsg
	}
	return nil
}

func (m *ExampleMsg) CloneVT() *ExampleMsg {
	if m == nil {
		return (*ExampleMsg)(nil)
	}
	r := new(ExampleMsg)
	r.ExampleField = m.ExampleField
	if rhs := m.OtherMsg; rhs != nil {
		r.OtherMsg = rhs.CloneVT()
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ExampleMsg) CloneMessageVT() any {
	return m.CloneVT()
}

func (this *ExampleMsg) EqualVT(that *ExampleMsg) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.ExampleField != that.ExampleField {
		return false
	}
	if !this.OtherMsg.EqualVT(that.OtherMsg) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ExampleMsg) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*ExampleMsg)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (m *ExampleMsg) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExampleMsg) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *ExampleMsg) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.OtherMsg != nil {
		size, err := m.OtherMsg.MarshalToSizedBufferVT(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ExampleField) > 0 {
		i -= len(m.ExampleField)
		copy(dAtA[i:], m.ExampleField)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ExampleField)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExampleMsg) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ExampleField)
	if l > 0 {
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	if m.OtherMsg != nil {
		l = m.OtherMsg.SizeVT()
		n += 1 + l + protohelpers.SizeOfVarint(uint64(l))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ExampleMsg) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protohelpers.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExampleMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExampleMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExampleField", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return protohelpers.ErrInvalidLength
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return protohelpers.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExampleField = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protohelpers.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return protohelpers.ErrInvalidLength
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return protohelpers.ErrInvalidLength
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OtherMsg == nil {
				m.OtherMsg = &other.OtherMsg{}
			}
			if err := m.OtherMsg.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := protohelpers.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protohelpers.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
