//go:build deps_only

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.45.1-0.20260203090429-3e915608d4e8
// source: github.com/aperturerobotics/common/example/example.proto

#include "example_srpc.pb.hpp"

namespace example {

starpc::Error SRPCEchoerClientImpl::Echo(const example::EchoMsg& in, example::EchoMsg* out) {
  return cc_->ExecCall(service_id_, "Echo", in, out);
}

std::vector<std::string> SRPCEchoerHandler::GetMethodIDs() const {
  return {
    "Echo",
  };
}

std::pair<bool, starpc::Error> SRPCEchoerHandler::InvokeMethod(
    const std::string& service_id,
    const std::string& method_id,
    starpc::Stream* strm) {
  if (!service_id.empty() && service_id != service_id_) {
    return {false, starpc::Error::OK};
  }

  if (method_id == "Echo") {
    example::EchoMsg req;
    starpc::Error err = strm->MsgRecv(&req);
    if (err != starpc::Error::OK) return {true, err};
    example::EchoMsg resp;
    err = impl_->Echo(req, &resp);
    if (err != starpc::Error::OK) return {true, err};
    return {true, strm->MsgSend(resp)};
  }

  return {false, starpc::Error::OK};
}

}  // namespace example
