//go:build deps_only && cgo

// Code generated by protoc-gen-starpc-cpp. DO NOT EDIT.
// protoc-gen-starpc-cpp version: v0.45.1-0.20260203090429-3e915608d4e8
// source: github.com/aperturerobotics/common/example/example.proto

#pragma once

#include <functional>
#include <memory>
#include <string>
#include <utility>

#include "srpc/starpc.hpp"

#include "example.pb.h"

namespace example {

// Service ID for Echoer
constexpr const char* kSRPCEchoerServiceID = "example.Echoer";


// SRPCEchoerClient is the client API for Echoer service.
class SRPCEchoerClient {
 public:
  virtual ~SRPCEchoerClient() = default;

  // SRPCClient returns the underlying SRPC client.
  virtual starpc::Client* SRPCClient() = 0;

  // Echo
  virtual starpc::Error Echo(const example::EchoMsg& in, example::EchoMsg* out) = 0;
};

// SRPCEchoerClientImpl implements SRPCEchoerClient.
class SRPCEchoerClientImpl : public SRPCEchoerClient {
 public:
  explicit SRPCEchoerClientImpl(starpc::Client* cc, const std::string& service_id = "")
      : cc_(cc), service_id_(service_id.empty() ? kSRPCEchoerServiceID : service_id) {}

  starpc::Client* SRPCClient() override { return cc_; }

  // Echo
  virtual starpc::Error Echo(const example::EchoMsg& in, example::EchoMsg* out) override;

 private:
  starpc::Client* cc_;
  std::string service_id_;
};

// NewSRPCEchoerClient creates a new client.
inline std::unique_ptr<SRPCEchoerClient> NewSRPCEchoerClient(starpc::Client* cc) {
  return std::make_unique<SRPCEchoerClientImpl>(cc);
}

// SRPCEchoerServer is the server API for Echoer service.
class SRPCEchoerServer {
 public:
  virtual ~SRPCEchoerServer() = default;

  // Echo
  virtual starpc::Error Echo(const example::EchoMsg& req, example::EchoMsg* resp) = 0;
};

// SRPCEchoerHandler implements starpc::Handler for Echoer.
class SRPCEchoerHandler : public starpc::Handler {
 public:
  SRPCEchoerHandler(SRPCEchoerServer* impl, const std::string& service_id = "")
      : impl_(impl), service_id_(service_id.empty() ? kSRPCEchoerServiceID : service_id) {}

  const std::string& GetServiceID() const override { return service_id_; }
  std::vector<std::string> GetMethodIDs() const override;
  std::pair<bool, starpc::Error> InvokeMethod(
      const std::string& service_id,
      const std::string& method_id,
      starpc::Stream* strm) override;

 private:
  SRPCEchoerServer* impl_;
  std::string service_id_;
};

// NewSRPCEchoerHandler creates a new handler for the given implementation.
inline std::unique_ptr<SRPCEchoerHandler> NewSRPCEchoerHandler(SRPCEchoerServer* impl) {
  return std::make_unique<SRPCEchoerHandler>(impl);
}

// SRPCRegisterEchoer registers the server implementation with the mux.
// The returned handler must outlive the mux registration.
inline std::pair<std::unique_ptr<SRPCEchoerHandler>, starpc::Error> SRPCRegisterEchoer(starpc::Mux* mux, SRPCEchoerServer* impl) {
  auto handler = NewSRPCEchoerHandler(impl);
  starpc::Error err = mux->Register(handler.get());
  if (err != starpc::Error::OK) {
    return {nullptr, err};
  }
  return {std::move(handler), starpc::Error::OK};
}

}  // namespace example
