//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/common/example/example.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "other/other.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto;
}  // extern "C"
namespace example {
class EchoMsg;
struct EchoMsgDefaultTypeInternal;
extern EchoMsgDefaultTypeInternal _EchoMsg_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull EchoMsg_class_data_;
class ExampleMsg;
struct ExampleMsgDefaultTypeInternal;
extern ExampleMsgDefaultTypeInternal _ExampleMsg_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ExampleMsg_class_data_;
}  // namespace example
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace example {

// ===================================================================


// -------------------------------------------------------------------

class EchoMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:example.EchoMsg) */ {
 public:
  inline EchoMsg() : EchoMsg(nullptr) {}
  ~EchoMsg() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EchoMsg* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EchoMsg));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EchoMsg(::google::protobuf::internal::ConstantInitialized);

  inline EchoMsg(const EchoMsg& from) : EchoMsg(nullptr, from) {}
  inline EchoMsg(EchoMsg&& from) noexcept
      : EchoMsg(nullptr, ::std::move(from)) {}
  inline EchoMsg& operator=(const EchoMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline EchoMsg& operator=(EchoMsg&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EchoMsg& default_instance() {
    return *reinterpret_cast<const EchoMsg*>(
        &_EchoMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(EchoMsg& a, EchoMsg& b) { a.Swap(&b); }
  inline void Swap(EchoMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EchoMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EchoMsg* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EchoMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EchoMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EchoMsg& from) { EchoMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EchoMsg* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "example.EchoMsg"; }

  explicit EchoMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EchoMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EchoMsg& from);
  EchoMsg(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EchoMsg&& from) noexcept
      : EchoMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBodyFieldNumber = 1,
  };
  // string body = 1;
  void clear_body() ;
  const ::std::string& body() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_body(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_body();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_body();
  void set_allocated_body(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_body() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_body(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_body();

  public:
  // @@protoc_insertion_point(class_scope:example.EchoMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EchoMsg& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr body_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull EchoMsg_class_data_;
// -------------------------------------------------------------------

class ExampleMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:example.ExampleMsg) */ {
 public:
  inline ExampleMsg() : ExampleMsg(nullptr) {}
  ~ExampleMsg() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ExampleMsg* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ExampleMsg));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExampleMsg(::google::protobuf::internal::ConstantInitialized);

  inline ExampleMsg(const ExampleMsg& from) : ExampleMsg(nullptr, from) {}
  inline ExampleMsg(ExampleMsg&& from) noexcept
      : ExampleMsg(nullptr, ::std::move(from)) {}
  inline ExampleMsg& operator=(const ExampleMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExampleMsg& operator=(ExampleMsg&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExampleMsg& default_instance() {
    return *reinterpret_cast<const ExampleMsg*>(
        &_ExampleMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ExampleMsg& a, ExampleMsg& b) { a.Swap(&b); }
  inline void Swap(ExampleMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExampleMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExampleMsg* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ExampleMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExampleMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExampleMsg& from) { ExampleMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ExampleMsg* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "example.ExampleMsg"; }

  explicit ExampleMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ExampleMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ExampleMsg& from);
  ExampleMsg(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ExampleMsg&& from) noexcept
      : ExampleMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExampleFieldFieldNumber = 1,
    kOtherMsgFieldNumber = 2,
  };
  // string example_field = 1;
  void clear_example_field() ;
  const ::std::string& example_field() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_example_field(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_example_field();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_example_field();
  void set_allocated_example_field(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_example_field() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_example_field(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_example_field();

  public:
  // .example.other.OtherMsg other_msg = 2;
  bool has_other_msg() const;
  void clear_other_msg() ;
  const ::example::other::OtherMsg& other_msg() const;
  [[nodiscard]] ::example::other::OtherMsg* PROTOBUF_NULLABLE release_other_msg();
  ::example::other::OtherMsg* PROTOBUF_NONNULL mutable_other_msg();
  void set_allocated_other_msg(::example::other::OtherMsg* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_other_msg(::example::other::OtherMsg* PROTOBUF_NULLABLE value);
  ::example::other::OtherMsg* PROTOBUF_NULLABLE unsafe_arena_release_other_msg();

  private:
  const ::example::other::OtherMsg& _internal_other_msg() const;
  ::example::other::OtherMsg* PROTOBUF_NONNULL _internal_mutable_other_msg();

  public:
  // @@protoc_insertion_point(class_scope:example.ExampleMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 40,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ExampleMsg& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr example_field_;
    ::example::other::OtherMsg* PROTOBUF_NULLABLE other_msg_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ExampleMsg_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExampleMsg

// string example_field = 1;
inline void ExampleMsg::clear_example_field() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.example_field_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ExampleMsg::example_field() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:example.ExampleMsg.example_field)
  return _internal_example_field();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ExampleMsg::set_example_field(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.example_field_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:example.ExampleMsg.example_field)
}
inline ::std::string* PROTOBUF_NONNULL ExampleMsg::mutable_example_field()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_example_field();
  // @@protoc_insertion_point(field_mutable:example.ExampleMsg.example_field)
  return _s;
}
inline const ::std::string& ExampleMsg::_internal_example_field() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.example_field_.Get();
}
inline void ExampleMsg::_internal_set_example_field(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.example_field_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ExampleMsg::_internal_mutable_example_field() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.example_field_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ExampleMsg::release_example_field() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:example.ExampleMsg.example_field)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.example_field_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.example_field_.Set("", GetArena());
  }
  return released;
}
inline void ExampleMsg::set_allocated_example_field(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.example_field_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.example_field_.IsDefault()) {
    _impl_.example_field_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:example.ExampleMsg.example_field)
}

// .example.other.OtherMsg other_msg = 2;
inline bool ExampleMsg::has_other_msg() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.other_msg_ != nullptr);
  return value;
}
inline const ::example::other::OtherMsg& ExampleMsg::_internal_other_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::example::other::OtherMsg* p = _impl_.other_msg_;
  return p != nullptr ? *p : reinterpret_cast<const ::example::other::OtherMsg&>(::example::other::_OtherMsg_default_instance_);
}
inline const ::example::other::OtherMsg& ExampleMsg::other_msg() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:example.ExampleMsg.other_msg)
  return _internal_other_msg();
}
inline void ExampleMsg::unsafe_arena_set_allocated_other_msg(
    ::example::other::OtherMsg* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.other_msg_);
  }
  _impl_.other_msg_ = reinterpret_cast<::example::other::OtherMsg*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:example.ExampleMsg.other_msg)
}
inline ::example::other::OtherMsg* PROTOBUF_NULLABLE ExampleMsg::release_other_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::example::other::OtherMsg* released = _impl_.other_msg_;
  _impl_.other_msg_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::example::other::OtherMsg* PROTOBUF_NULLABLE ExampleMsg::unsafe_arena_release_other_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:example.ExampleMsg.other_msg)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::example::other::OtherMsg* temp = _impl_.other_msg_;
  _impl_.other_msg_ = nullptr;
  return temp;
}
inline ::example::other::OtherMsg* PROTOBUF_NONNULL ExampleMsg::_internal_mutable_other_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.other_msg_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::example::other::OtherMsg>(GetArena());
    _impl_.other_msg_ = reinterpret_cast<::example::other::OtherMsg*>(p);
  }
  return _impl_.other_msg_;
}
inline ::example::other::OtherMsg* PROTOBUF_NONNULL ExampleMsg::mutable_other_msg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::example::other::OtherMsg* _msg = _internal_mutable_other_msg();
  // @@protoc_insertion_point(field_mutable:example.ExampleMsg.other_msg)
  return _msg;
}
inline void ExampleMsg::set_allocated_other_msg(::example::other::OtherMsg* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.other_msg_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.other_msg_ = reinterpret_cast<::example::other::OtherMsg*>(value);
  // @@protoc_insertion_point(field_set_allocated:example.ExampleMsg.other_msg)
}

// -------------------------------------------------------------------

// EchoMsg

// string body = 1;
inline void EchoMsg::clear_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& EchoMsg::body() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:example.EchoMsg.body)
  return _internal_body();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void EchoMsg::set_body(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.body_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:example.EchoMsg.body)
}
inline ::std::string* PROTOBUF_NONNULL EchoMsg::mutable_body()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:example.EchoMsg.body)
  return _s;
}
inline const ::std::string& EchoMsg::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_.Get();
}
inline void EchoMsg::_internal_set_body(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL EchoMsg::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.body_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE EchoMsg::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:example.EchoMsg.body)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.body_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.body_.Set("", GetArena());
  }
  return released;
}
inline void EchoMsg::set_allocated_body(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.body_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.body_.IsDefault()) {
    _impl_.body_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:example.EchoMsg.body)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace example


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2fcommon_2fexample_2fexample_2eproto_2epb_2eh
