// @generated
// This file is @generated by prost-build.
/// OtherMsg is a different message from ExampleMsg.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtherMsg {
    /// FooField is an example field.
    #[prost(uint32, tag="1")]
    pub foo_field: u32,
}
// @@protoc_insertion_point(module)
