package sourcecontract

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

func TestCheckSelectsProjectSources(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "tracked\nname.go", "package fixture\n\nfunc tracked() {}\n")
	writeSource(t, root, "nested/untracked\nname.proto", "syntax = \"proto3\";\nmessage Untracked {}\n")
	writeSource(t, root, "ignored.go", "package fixture\n\nfunc ignored() {}\n")
	writeSource(t, root, "notes.txt", "func irrelevant() {}\n")
	writeSource(t, root, ".gitignore", "ignored.go\n")
	runGit(t, root, "add", "tracked\nname.go", ".gitignore", "notes.txt")

	err := Check(root)
	assertDiagnostics(t, err, "tracked\nname.go", "nested/untracked\nname.proto")
	assertNoDiagnostics(t, err, "ignored.go", "notes.txt")
}

func TestCheckAppliesExactExclusions(t *testing.T) {
	root := newGitProject(t)
	for _, path := range []string{
		"vendor/bad.go", "node_modules/bad.go", ".tools/bad.go",
		"vendorx/bad.go", "node_modules-old/bad.go", ".toolshed/bad.go",
	} {
		writeSource(t, root, path, "package fixture\n\nfunc bad() {}\n")
	}

	err := Check(root)
	assertDiagnostics(t, err, "vendorx/bad.go", "node_modules-old/bad.go", ".toolshed/bad.go")
	assertNoDiagnostics(t, err, "vendor/bad.go", "node_modules/bad.go", ".tools/bad.go")
}

func TestCheckSkipsGeneratedSources(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "line-one.go", generatedGo(1))
	writeSource(t, root, "line-twenty.go", generatedGo(20))
	writeSource(t, root, "line-twenty-one.go", generatedGo(21))
	writeSource(t, root, "near-marker.go", "// Code generated by fixture. DO NOT EDIT\npackage fixture\n\nfunc nearMarker() {}\n")
	writeSource(t, root, "schema.pb.proto", invalidProto("Generated"))
	writeSource(t, root, "schema_pb.proto", invalidProto("Generated"))
	writeSource(t, root, "schema.pb.proto.bak.proto", invalidProto("SuffixLookalike"))

	err := Check(root)
	assertDiagnostics(t, err, "line-twenty-one.go", "near-marker.go", "schema.pb.proto.bak.proto")
	assertNoDiagnostics(t, err, "line-one.go", "line-twenty.go", "schema.pb.proto:", "schema_pb.proto:")
}

func TestCheckRejectsNonregularCandidateWithoutFollowingIt(t *testing.T) {
	root := newGitProject(t)
	outside := filepath.Join(t.TempDir(), "outside.go")
	if err := os.WriteFile(outside, []byte("package fixture\n\nfunc followed() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "link.go")); err != nil {
		t.Fatal(err)
	}

	err := Check(root)
	assertDiagnostics(t, err, "link.go", "nonregular")
	assertNoDiagnostics(t, err, "followed")
}

func TestCheckCoversEveryGoDeclarationAndField(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "contracts.go", `package fixture

const ( ExportedConstant = 1; privateConstant = 2 )
var ( ExportedVariable = 1; privateVariable = 2 )
type ExportedType struct { ExportedField string; privateField string }
type privateType interface { Call() }
func ExportedFunction() {}
func privateFunction() {}
func (ExportedType) ExportedMethod() {}
func (ExportedType) privateMethod() {}
`)
	writeSource(t, root, "contracts_test.go", `package fixture

import "testing"
func TestContract(t *testing.T) {}
func testHelper() {}
`)

	err := Check(root)
	for _, identifier := range []string{
		"ExportedConstant", "privateConstant", "ExportedVariable", "privateVariable",
		"ExportedType", "ExportedField", "privateField", "privateType",
		"ExportedFunction", "privateFunction", "ExportedMethod", "privateMethod",
		"TestContract", "testHelper",
	} {
		assertDiagnostics(t, err, identifier)
	}
}

func TestCheckRequiresExactGoCommentShape(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "comments.go", `package fixture

// WrongName describes ExactName.
func ExactName() {}

// privateName describes the function
func privateName() {}

// AcceptedName describes the function.
func AcceptedName() {}
`)

	err := Check(root)
	assertDiagnostics(t, err, "ExactName", "privateName")
	assertNoDiagnostics(t, err, "AcceptedName")
}

func TestCheckCoversProtobufDeclarationsAndMembers(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "contract.proto", `syntax = "proto3";

extend google.protobuf.MethodOptions { string extension_name = 50001; }
enum State { STATE_UNKNOWN = 0; STATE_READY = 1; }
message Outer {
  enum NestedState { NESTED_STATE_UNKNOWN = 0; }
  message Nested { string nested_value = 1; }
  string ordinary_field = 1;
  oneof payload { string text_value = 2; bytes raw_value = 3; }
}
service Records { rpc Read(Outer) returns (Outer); }
`)

	err := Check(root)
	for _, identifier := range []string{
		"ExtensionName", "State", "STATE_UNKNOWN", "STATE_READY", "Outer", "NestedState",
		"NESTED_STATE_UNKNOWN", "Nested", "NestedValue", "OrdinaryField", "TextValue", "RawValue", "Records", "Read",
	} {
		assertDiagnostics(t, err, identifier)
	}
}

func TestCheckRequiresExactProtobufCommentShape(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "comments.proto", `syntax = "proto3";

// WrongName describes Record.
message Record {
  // RecordKey identifies the record
  string record_key = 1;
}
`)

	err := Check(root)
	assertDiagnostics(t, err, "Record", "RecordKey")
}

func TestCheckRejectsProtobufLayoutAndZeroValueViolations(t *testing.T) {
	tests := map[string]string{
		"one-line-message": `// Record contains a value.
message Record { string value = 1; }`,
		"one-line-enum": `// State describes state.
enum State { STATE_UNKNOWN = 0; }`,
		"members-share-line": `// Record contains values.
message Record {
  // First identifies the first value.
  string first = 1; string second = 2;
}`,
		"rpc-shares-line": `// Records serves records.
service Records { // Read reads a record.
  rpc Read(Record) returns (Record); rpc Write(Record) returns (Record);
}`,
		"missing-separation": `// First contains a value.
message First {
}
// Second contains a value.
message Second {
}`,
		"excess-separation": `// First contains a value.
message First {
}


// Second contains a value.
message Second {
}`,
		"wrong-zero": `// State describes state.
enum State {
  // STATE_UNSPECIFIED is the default state.
  STATE_UNSPECIFIED = 0;
}`,
	}
	for name, source := range tests {
		t.Run(name, func(t *testing.T) {
			root := newGitProject(t)
			writeSource(t, root, "layout.proto", "syntax = \"proto3\";\n\n"+source+"\n")
			if err := Check(root); err == nil {
				t.Fatal("Check() unexpectedly accepted invalid protobuf layout")
			}
		})
	}
}

func TestCheckPreservesMultilineDeclarationsAndLiteralBraces(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "valid.proto", `syntax = "proto3";

// State describes record state.
enum State
{
  // STATE_UNKNOWN is the default record state.
  STATE_UNKNOWN = 0;
}

// Record contains a key.
message Record
{
  // Key identifies the record.
  string key = 1 [json_name = "key{}/*not a comment*/"];
}

// Records serves record operations.
service Records
{
  // Read reads a record.
  rpc Read(Record) returns (Record) {
    option deprecated = false; // } ignored
  }
}
`)
	if err := Check(root); err != nil {
		t.Fatalf("Check() rejected valid multiline source: %v", err)
	}
}

func TestCheckReturnsDeterministicDiagnostics(t *testing.T) {
	root := newGitProject(t)
	writeSource(t, root, "ordered.go", `package fixture

const (alpha = 1; beta = 2)






func later() {}
`)
	writeSource(t, root, "rules.proto", `syntax = "proto3";
message Record { string value = 1; }
`)
	writeSource(t, root, "z.go", "package fixture\n\nfunc zed() {}\n")

	first := Check(root)
	second := Check(root)
	if first == nil || second == nil || first.Error() != second.Error() {
		t.Fatalf("diagnostics differ:\nfirst: %v\nsecond: %v", first, second)
	}
	records := parseDiagnosticRecords(t, first.Error())
	if len(records) < 6 {
		t.Fatalf("too few diagnostic records to exercise ordering: %v", first)
	}
	for index := 1; index < len(records); index++ {
		if diagnosticRecordLess(records[index], records[index-1]) {
			t.Fatalf("diagnostics are not path-byte/line/column/rule sorted at %q then %q", records[index-1].raw, records[index].raw)
		}
	}

	var numericLine, numericColumn, ruleTie bool
	for index := 1; index < len(records); index++ {
		previous, current := records[index-1], records[index]
		if previous.path == current.path && previous.line < current.line && current.line >= 10 {
			numericLine = true
		}
		if previous.path == current.path && previous.line == current.line && previous.column < current.column {
			numericColumn = true
		}
		if previous.path == current.path && previous.line == current.line && previous.column == current.column && previous.rule < current.rule {
			ruleTie = true
		}
	}
	if !numericLine || !numericColumn || !ruleTie {
		t.Fatalf("fixtures did not exercise numeric line, numeric column, and rule tie ordering: line=%t column=%t rule=%t\n%v", numericLine, numericColumn, ruleTie, first)
	}
}

type diagnosticRecord struct {
	raw    string
	path   string
	line   int
	column int
	rule   string
}

var diagnosticRecordPattern = regexp.MustCompile(`^([^:]+):([0-9]+):([0-9]+): ([^:]+): .+$`)

func parseDiagnosticRecords(t *testing.T, diagnostics string) []diagnosticRecord {
	t.Helper()
	var records []diagnosticRecord
	for _, line := range strings.Split(diagnostics, "\n") {
		match := diagnosticRecordPattern.FindStringSubmatch(line)
		if match == nil {
			continue
		}
		lineNumber, err := strconv.Atoi(match[2])
		if err != nil {
			t.Fatal(err)
		}
		column, err := strconv.Atoi(match[3])
		if err != nil {
			t.Fatal(err)
		}
		records = append(records, diagnosticRecord{
			raw: line, path: match[1], line: lineNumber, column: column, rule: match[4],
		})
	}
	return records
}

func diagnosticRecordLess(left, right diagnosticRecord) bool {
	if pathOrder := bytes.Compare([]byte(left.path), []byte(right.path)); pathOrder != 0 {
		return pathOrder < 0
	}
	if left.line != right.line {
		return left.line < right.line
	}
	if left.column != right.column {
		return left.column < right.column
	}
	return left.rule < right.rule
}

func newGitProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	runGit(t, root, "init", "--quiet")
	return root
}

func writeSource(t *testing.T, root, name, source string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
}

func runGit(t *testing.T, root string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = root
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, output)
	}
}

func assertDiagnostics(t *testing.T, err error, wants ...string) {
	t.Helper()
	if err == nil {
		t.Fatalf("Check() succeeded, want diagnostics containing %v", wants)
	}
	for _, want := range wants {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("Check() error does not contain %q: %v", want, err)
		}
	}
}

func assertNoDiagnostics(t *testing.T, err error, rejects ...string) {
	t.Helper()
	if err == nil {
		return
	}
	for _, reject := range rejects {
		if strings.Contains(err.Error(), reject) {
			t.Errorf("Check() error unexpectedly contains %q: %v", reject, err)
		}
	}
}

func generatedGo(markerLine int) string {
	lines := make([]string, markerLine-1)
	for index := range lines {
		lines[index] = "// preamble"
	}
	lines = append(lines, "// Code generated by fixture. DO NOT EDIT.", "package fixture", "", "func generated() {}")
	return strings.Join(lines, "\n") + "\n"
}

func invalidProto(name string) string {
	return "syntax = \"proto3\";\nmessage " + name + " {}\n"
}
